#!/usr/bin/env node
// Build script for dithr editor cart.
// Concatenates source modules into dist/main.js in dependency order.
// Usage: node build.js

const fs = require("fs");
const path = require("path");

const srcDir = path.join(__dirname, "src");
const distDir = path.join(__dirname, "dist");

// Files in dependency order — later files may reference earlier globals.
const modules = [
    "config.js",
    "state.js",
    "helpers.js",
    "tokenizer.js",
    "buffer.js",
    "edit.js",
    "vim.js",
    "draw.js",
    "find.js",
    "browser.js",
    "main.js",
];

if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
}

const header = `// ─── dithr editor (built) ─────────────────────────────────────────────────────
// Auto-generated by build.js — do not edit directly.
// Edit the source files in src/ and rebuild.
// ──────────────────────────────────────────────────────────────────────────────
`;

let output = header;

for (const mod of modules) {
    const filePath = path.join(srcDir, mod);
    if (!fs.existsSync(filePath)) {
        console.error("Missing source file: " + mod);
        process.exit(1);
    }
    const content = fs.readFileSync(filePath, "utf-8");
    output += "\n// ── " + mod + " " + "─".repeat(Math.max(0, 68 - mod.length)) + "\n\n";
    output += content + "\n";
}

fs.writeFileSync(path.join(distDir, "main.js"), output, "utf-8");
console.log("Built dist/main.js (" + modules.length + " modules)");
